
spring:
  datasource:
    url: jdbc:mysql://localhost:3333/book?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: decent_backend_user
    password: my_secret_password
    platform: mysql
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: false
logging:
  level:
    org.springframework.security: info
server:
  port: 8070
---

spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
